### ISSUE TITLE
weird shape when resize the button!

### ISSUE THREAD

**Issue by masoud-c** [recruit-lifestyle/PlayPauseButton#1]
hi
when i change the size to 50x50 it's getting a weird shape...
why that happens?

**Comment by amyu** [comment]
Thanks @masoudfcr !

```
<jp.co.recruit_lifestyle.android.widget.PlayPauseButton
        android:layout_width="50dp"
        android:layout_height="50dp"
        android:layout_centerInParent="true"
        android:id="@+id/main_play_pause_button"
        />
```

![](https://i.gyazo.com/41d05ffa7d256b74452b9ad30a7e2f73.png)

Sorry, I do not understand about it.
Please give more information or sample code, project.
