### ISSUE TITLE
setcolor issue

### ISSUE THREAD

**Issue by andyrosty** [recruit-lifestyle/PlayPauseButton#2]
hello i tried changing the color and i keep getting a grey color no matter what color i use.
Here is my code in my activity:

playPauseButton.setColor(R.color.myColor);

I'll like to know if there is another way i can change the color ?

**Comment by amyu** [comment]
Thanks @andyrosty  !

Please wait a minute.
I will check it!!!!!
(_ﾉω・_)

**Comment by amyu** [comment]
@andyrosty 
Please try this!

```
playPauseButton.setColor(ContextCompat.getColor(context, R.color.myColor));
```

**Comment by andyrosty** [comment]
wow...thanks so much worked for me.I just had to change the code a little.

playPauseButton.setColor(ContextCompat.getColor(getBaseContext(), R.color.myColor));

Thanks once more.

**Comment by amyu** [comment]
Please contact us if there is a bug ლ(´ڡ`ლ)
Thanks!
